In [8]:
import numpy
l1=[1,2,3,4,5]
s={5,6,7,8,9}
d=(1,3,5,7,)
arr=numpy.array(l1)
arr2=numpy.array(s)
arr3=numpy.array(d)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr2

array({5, 6, 7, 8, 9}, dtype=object)

In [7]:
arr3

array([1, 3, 5, 7])

In [14]:
class c1:
  name="sindhu"
  age=20

obj=c1()
print(obj.name)
print(obj.age)


sindhu
20


In [13]:
s1={1,2,3,[2,3,4]}
print(s1)

TypeError: unhashable type: 'list'

In [16]:
t1="hello"
ar1=numpy.array(t1)
ar1

array('hello', dtype='<U5')

In [17]:
ar1.dtype

dtype('<U5')

In [18]:
type(arr)

numpy.ndarray

In [19]:
type(list(arr))

list

In [20]:
s={1,2,3}

list(s)

[1, 2, 3]

In [21]:
tuple(s)

(1, 2, 3)

In [22]:
l=[1,2,3]

arr=[1,2,3]

arr

[1, 2, 3]

In [24]:
arr*2


[1, 2, 3, 1, 2, 3]

In [25]:

arr=[1,2,3]
arr*2

[1, 2, 3, 1, 2, 3]

In [26]:
ar2=[1,2,3.45,89,2]
np_ar=np.array(ar2)

np_ar

array([ 1.  ,  2.  ,  3.45, 89.  ,  2.  ])

In [27]:
new_ar=np.append(np_ar,78)
new_ar

array([ 1.  ,  2.  ,  3.45, 89.  ,  2.  , 78.  ])

In [28]:
#to add multiple values
new_ar=np.append(np_ar,[56,33,35])
new_ar

array([ 1.  ,  2.  ,  3.45, 89.  ,  2.  , 56.  , 33.  , 35.  ])

In [48]:
#insert
#based on index value to add ele into array
#np.insert(array_to_be_modified,index position,value)
new_ar=np.insert(np_ar,2,123)
new_ar


array([  1.  ,   2.  , 123.  ,   3.45,  89.  ,   2.  ])

In [31]:
#delete ele from an array
nr=np.delete(np_ar,np.where(np_ar==1))
nr

array([ 2.  ,  3.45, 89.  ,  2.  ])

In [32]:
#to del no of values in array
nr=np.setdiff1d(np_ar,[5.0,3.45])
nr

array([ 1.,  2., 89.])

In [33]:
#to delete based on index pos
nr=np.delete(np_ar,0)
nr


array([ 2.  ,  3.45, 89.  ,  2.  ])

In [36]:
#filter in numpy array
new_ar<30

array([ True,  True, False,  True, False,  True])

In [38]:
new_ar[new_ar<30]

array([1.  , 2.  , 3.45, 2.  ])

In [39]:
#to print values <20 and >50
#for and operation using &
#for or op using |
(new_ar>20) & (new_ar<50)

array([False, False, False, False, False, False])

In [42]:
new_ar[(new_ar>20)&(new_ar<50)]

TypeError: '>' not supported between instances of 'list' and 'int'

In [49]:
new_ar

array([  1.  ,   2.  , 123.  ,   3.45,  89.  ,   2.  ])

In [50]:
#to replace value in array
new_ar[new_ar==3.45]=56

new_ar

array([  1.,   2., 123.,  56.,  89.,   2.])

In [51]:
#to create 1d array full of 0
np.zeros(6)


array([0., 0., 0., 0., 0., 0.])

In [52]:
#to create 2d array full of 0
#syntax=np.zeros([no of rows,no of col])
np.zeros([2,2])


array([[0., 0.],
       [0., 0.]])

In [53]:
#to create array full of 1
np.ones(6)

new_ar


array([  1.,   2., 123.,  56.,  89.,   2.])

In [54]:
#to create 2d array full of 1
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
#type convert ele in array
#to find numpy data type of ele present in array-->dtype
#type(np_ar)
np_ar.dtype

dtype('float64')

In [56]:
#we can convert values in numpy array into various bits
#they are
#int8,int16,int32,int64
#float16,float32,float64
#complex64,complex128
#unit16,unit32

np_ar=np.zeros([2,4],dtype='int16')
np_ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [57]:
np_ar=np.zeros([2,4],dtype='uint32')
np_ar


array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint32)

In [58]:
np.int16(np_ar)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)