In [2]:
import numpy as np
ar1=np.arange(13)

In [4]:
ar1
len(ar1)

13

In [10]:
reshpd_array=ar1.reshape(1,13)
reshpd_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [7]:
#identity matrix can be created using 2 functions
#eye()->used to define both user defined rows and colimns
#identity()->used to define same no.of rows and colums
#syntax->np.eye(3,4) 3 rows,4 columns
#syntax->np.identity(5) 5 rows 5 columns
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [8]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.identity(5,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [11]:
ar2=np.arange(25)

In [12]:
ar2


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
#to perform multidimensional slicing
ar2=np.arange(25).reshape(5,5)
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
ar2.shape


(5, 5)

In [20]:
#ar2[rows:step,columns:step]
#arr[row_start:row_end,column_start:column_end]
ar2[0:4]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
ar2[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [30]:
ar2[-3:-1,-3:-1]

array([[12, 13],
       [17, 18]])

In [32]:
ar3=np.arange(50).reshape(5,10)
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [33]:
#linshape
np.sum(ar3)

1225

In [35]:
ar3.sum(axis=0)#to add based on column wise

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [80]:
np.sum(ar3,axis=1)#to add based on row wise

array([ 45, 145, 245, 345, 445])

In [38]:
np.product(ar3)

0

In [39]:
#mean->average
#median->middle value
#mode->repeated value
#variance->median/total no.of elements
#std->sqrt of variance

In [40]:
#linspace
#it is used to print evenly seperated pointed 
#between 2 range of values
#linsapce(start,end,no.of parts)
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [41]:
np.linspace(1,10,3,dtype=int)

array([ 1,  5, 10])

In [43]:
np.linspace(1,10,3,retstep=True)

(array([ 1. ,  5.5, 10. ]), 4.5)

In [45]:
#random module
#to generate random number between the range
#np.random.randint(start,end)
np.random.randint(33,40)

34

In [46]:
np.random.randint(40)

15

In [47]:
np.random.randint(1,40,5)

array([26, 12, 25, 25, 37])

In [48]:
# rand()
# to get randomly generated values from 0 to 1 based on uniform distribution
np.random.rand(4)

array([0.66458454, 0.9559784 , 0.01375653, 0.09966423])

In [49]:
# randn()
# to get randomly generated values from 0 to 1 based on normalized distribution
np.random.randn(5)

array([-1.27052842,  0.11556954,  0.04948889,  1.8810758 , -0.51008218])

In [51]:
np.random.randn(5,4)

array([[ 0.04577448,  0.47879798, -0.21949395,  0.40719152],
       [ 0.06714588, -0.11777682,  0.04159087, -1.30116967],
       [-0.58075158, -0.00417807,  0.50392198, -1.24426819],
       [ 1.8546837 ,  0.86434219,  1.33616824,  0.07490408],
       [ 0.24297329, -1.05938468,  0.31799284, -0.26944804]])

In [52]:
ar3.min()

0

In [53]:
ar3.max()

49

In [54]:
print(ar3.argmax())

49


In [56]:
l1=[11,3,67,34,43]
np1=np.array(l1)
#to find the min value index pos in an array
print(np1.argmin())
#to find the max value index pos in an array
print(np1.argmax())

1
2


In [57]:
np1

array([11,  3, 67, 34, 43])

In [59]:
np.sin(np1)


array([-0.99999021,  0.14112001, -0.85551998,  0.52908269, -0.83177474])

In [61]:
np.cos(np1)

array([ 0.0044257 , -0.9899925 , -0.5177698 , -0.84857027,  0.5551133 ])

In [62]:
np.tan(np1)

array([-2.25950846e+02, -1.42546543e-01,  1.65231726e+00, -6.23498963e-01,
       -1.49838734e+00])

In [63]:
np.sin(np1)/np.cos(np1)

array([-2.25950846e+02, -1.42546543e-01,  1.65231726e+00, -6.23498963e-01,
       -1.49838734e+00])

In [76]:
np2=np.array([1,2,3,])
np3=np.array([4,5,6])
#(1*4)+(2*5)*(3*6)=4+10+18=32
np4=np2*np3
np.array(np4)

array([ 4, 10, 18])

In [81]:
np.sum(np4)

32

In [83]:
fname=np.array(["sid","fn1","fn2"])
lname=np.array(["sid","ln1","ln2"])
#fname.tostring()

In [7]:
import numpy as np
np2=np.array([1,2,3,4,7])
np3=np.array([4,5,6])
len1=len(np2)
len2=len(np3)
diff=abs(len1-len2)
for val in range(diff):
    np3=np.append(np3,1)
np.sum(np2*np3)

43

In [8]:
np1=np.array([1,2,3,4,7,np.nan,np.nan])

In [9]:
#to print nan values
np1[np.isnan(np1)]

array([nan, nan])

In [11]:
#to eleminate nan values
np1[~np.isnan(np1)]

array([1., 2., 3., 4., 7.])