In [ ]:

# from google.colab import drive
# drive.mount('/content/gdrive')

# Project 2:
# Detect flowers based on images

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import style

# Model_selection
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder

# preprocess
from keras.preprocessing.image import ImageDataGenerator

from keras import backend as K
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam, SGD, Adagrad, Adadelta, RMSprop
from keras.utils import to_categorical

from keras.layers import Dropout, Flatten, Activation
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization

import tensorflow as tf
import random as rn

import cv2
import numpy as np
from tqdm import tqdm
import os
from random import shuffle
from zipfile import ZipFile
from PIL import Image

In [ ]:
X=[]
Z=[]
IMG_SIZE=150
FLOWER_DAISEY_DIR = '/content/gdrive/MyDrive/archive (4)-20240220T012139Z-001/archive (4)/train/daisy'
FLOWER_SUNFLOWER_DIR = '/content/gdrive/MyDrive/archive (4)-20240220T012139Z-001/archive (4)/train/sunflower'
FLOWER_TULIP_DIR = '/content/gdrive/MyDrive/archive (4)-20240220T012139Z-001/archive (4)/train/tulip'
FLOWER_DANDI_DIR = '/content/gdrive/MyDrive/archive (4)-20240220T012139Z-001/archive (4)/train/dandelion'
FLOWER_ROSE_DIR = '/content/gdrive/MyDrive/archive (4)-20240220T012139Z-001/archive (4)/train/rose'

In [ ]:
def assign_label(img, flower_type):
  return flower_type

In [ ]:
# tqdm --> It creates a progress bar from the loop
def make_train_data(flower_type, DIR):
  for img in tqdm(os.listdir(DIR)):
    label = assign_label(img, flower_type)
    path = os.path.join(DIR, img)
    img = cv2.imread(path, cv2.IMREAD_COLOR)
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

    X.append(np.array(img))
    Z.append(str(label))

In [ ]:
make_train_data('Daisy', FLOWER_DAISEY_DIR)
print(len(X))

FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/MyDrive/archive (4)-20240220T012139Z-001/archive (4)/train/daisy'

In [ ]:
make_train_data('Sunflower', FLOWER_SUNFLOWER_DIR)
print(len(X))

In [ ]:
make_train_data('Daisy', FLOWER_DAISEY_DIR)
print(len(X))

In [ ]:

make_train_data('dandelion', FLOWER_DANDI_DIR)
print(len(X))

In [ ]:
make_train_data('Rose', FLOWER_ROSE_DIR)
print(len(X))

In [ ]:
fig, ax = plt.subplots(5, 2)
fig.set_size_inches(15, 15)

for row in range(5):
  for col in range(2):
    l= rn.randint(0, len(Z))
    ax[row, col].imshow(X[l])
    ax[row, col].set_title("Flower: "+Z[l])

  plt.tight_layout()

In [ ]:
#encoding all the flower names
le=LabelEncoder()
y=le.fit_transform(Z)
y=to_categorical(y,5)
x=np.array(X)
x=x/255
# x-->contains all the image array
# y-->contains all the image names
print(x)

[[[[0.24313725 0.21960784 0.32941176]
   [0.33333333 0.31764706 0.42745098]
   [0.34509804 0.33333333 0.45490196]
   ...
   [0.35294118 0.34509804 0.50588235]
   [0.35294118 0.32156863 0.4627451 ]
   [0.29803922 0.25490196 0.34117647]]

  [[0.25882353 0.24705882 0.34509804]
   [0.30196078 0.29019608 0.39215686]
   [0.31764706 0.33333333 0.47843137]
   ...
   [0.34117647 0.30980392 0.45882353]
   [0.30588235 0.30196078 0.42352941]
   [0.27058824 0.23921569 0.34117647]]

  [[0.27843137 0.2627451  0.40392157]
   [0.25490196 0.2627451  0.40784314]
   [0.34117647 0.35294118 0.51372549]
   ...
   [0.34117647 0.32156863 0.44313725]
   [0.38823529 0.34901961 0.47843137]
   [0.31764706 0.28627451 0.38039216]]

  ...

  [[0.3372549  0.50980392 0.38431373]
   [0.47843137 0.6        0.47058824]
   [0.38431373 0.50980392 0.36862745]
   ...
   [0.20784314 0.16862745 0.20392157]
   [0.18039216 0.16862745 0.23137255]
   [0.18823529 0.14901961 0.23137255]]

  [[0.30588235 0.49019608 0.35686275]
   [0.4

In [ ]:
print(y)

[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [ ]:
# spliting to test and train dataset
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)

In [ ]:
print(Z)

['Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Daisy', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'Sunflower', 'S

In [ ]:
#set random seed
np.random.seed(42)
rn.seed(42)
tf.random.set_seed(42)

In [ ]:
#building the model
model=Sequential()
model.add(Conv2D(filters=32,kernel_size=(5,5),padding='same',activation='relu',input_shape=(150,150,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
#1 2 3 4
#5 6 7 8
#9 10 11 12
#13 14 15 16

#MaxPooling --->2x2
#6 8
#14 16
model.add(Conv2D(filters=64,kernel_size=(3,3),padding='same',activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2)))

model.add(Conv2D(filters=96,kernel_size=(3,3),padding='same',activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2)))
model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dense(5,activation='softmax'))


In [ ]:
#adjust the learning rate
batch_size=128
epochs=50

from keras.callbacks import ReduceLROnPlateau
red_lr=ReduceLROnPlateau(monitor='val_acc',patience=3,verbose=1,factor=0)


In [ ]:
#to prevent overfitting
datagen=ImageDataGenerator(
    featurewise_center=False,
   samplewise_center= False,
    featurewise_std_normalization=False,
    samplewise_std_normalization=False,
    zca_whitening=False,
    rotation_range=10,
    zoom_range=0.1,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    vertical_flip=False)
datagen.fit(x_train)

In [ ]:
#compile keras model
model.compile(optimizer=Adam(lr=0.001),loss='categorical_crossentropy',metrics=['accuracy'])



In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 150, 150, 32)      2432      
                                                                 
 max_pooling2d (MaxPooling2  (None, 75, 75, 32)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 75, 75, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 37, 37, 64)        0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 37, 37, 96)        55392     
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 18, 18, 96)        0

In [ ]:
#fitting on training and making predictions
History=model.fit_generator(datagen.flow(x_train,y_train,batch_size=batch_size),epochs=epochs,validation_data=(x_test,y_test),
                            verbose=1,steps_per_epoch=x_train.shape[0]//batch_size)

<ipython-input-52-1d9c612dc1fb>:2: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  History=model.fit_generator(datagen.flow(x_train,y_train,batch_size=batch_size),epochs=epochs,validation_data=(x_test,y_test),


Epoch 1/50
11/11 [==============================] - 97s 8s/step - loss: 1.7532 - accuracy: 0.4035 - val_loss: 1.0775 - val_accuracy: 0.5056
Epoch 2/50
11/11 [==============================] - 97s 9s/step - loss: 1.0430 - accuracy: 0.5610 - val_loss: 0.9166 - val_accuracy: 0.6517
Epoch 3/50
11/11 [==============================] - 93s 8s/step - loss: 0.9053 - accuracy: 0.6559 - val_loss: 0.8882 - val_accuracy: 0.6292
Epoch 4/50
11/11 [==============================] - 95s 9s/step - loss: 0.8642 - accuracy: 0.6597 - val_loss: 0.7754 - val_accuracy: 0.6994
Epoch 5/50
11/11 [==============================] - 92s 8s/step - loss: 0.8909 - accuracy: 0.6381 - val_loss: 0.7854 - val_accuracy: 0.6798
Epoch 6/50
11/11 [==============================] - 93s 8s/step - loss: 0.8163 - accuracy: 0.6829 - val_loss: 0.7195 - val_accuracy: 0.7303
Epoch 7/50
11/11 [==============================] - 93s 9s/step - loss: 0.7483 - accuracy: 0.7052 - val_loss: 0.6682 - val_accuracy: 0.7444
Epoch 8/50
11/11 [==

NameError: name 'History' is not defined